id: PA6AD8958
initial_creation_type: input
source_metadata:
  title: Bodhisatvapiṭaka
  language: en
  volumes:
    69304a0d2de04b94ac34c27acbcfe6ae:
      title: CI_Folio 2a
      base_file: CI_Folio 2a.txt
      work_id: W78D83D43
    3b74ccf066d3435e9587cba506fd1a75:
      title: CI_Folio 2b
      base_file: CI_Folio 2b.txt
      work_id: WBB452894
    e346e8ffecbd4b22b824e59985e0ae06:
      title: CI_Folio 3a
      base_file: CI_Folio 3a.txt
      work_id: WE1AC8B61
    780eaba62ff34b7584a61bc30fdc4e9e:
      title: CI_Folio 3b
      base_file: CI_Folio 3b.txt
      work_id: WB784262B
    8091a5245216495eb7e069ee1d7f7f02:
      title: CI_Folio 4a
      base_file: CI_Folio 4a.txt
      work_id: W246B4D7B
    3df396b098c1487187fd698f55491abc:
      title: CI_Folio 4b
      base_file: CI_Folio 4b.txt
      work_id: W54D7885B
    4b83d7a9e93544e19e96c5c2bfa7677c:
      title: CI_Folio 5a
      base_file: CI_Folio 5a.txt
      work_id: WC0641009
    f3f684db53fe45c3970cde962042c6ba:
      title: CI_Folio 5b
      base_file: CI_Folio 5b.txt
      work_id: WE3A145BC
    05e67bb97a6b4494b2973fe2f9744d30:
      title: CI_Folio 6a
      base_file: CI_Folio 6a.txt
      work_id: W40DD0BA9
    e0b27bc8f6754c58bd38a7594da50540:
      title: 'Chapter 10: Dhyānapāramitā'
      base_file: 'Chapter 10: Dhyānapāramitā.txt'
      work_id: W9404E4C4
    511c27e6bf0e43a3b255e5f725127d45:
      title: 'Chapter 11: Prajñāpāramitā'
      base_file: 'Chapter 11: Prajñāpāramitā.txt'
      work_id: W5844234F
    1f92df640eb14891a60857e99f2274de:
      title: 'Chapter 2: Kimbhīrayakṣa'
      base_file: 'Chapter 2: Kimbhīrayakṣa.txt'
      work_id: W7C557244
    ae8b678c39dd448bbd21cb5ed33e86fb:
      title: 'Chapter 3: Bodhisatvaparīkṣā'
      base_file: 'Chapter 3: Bodhisatvaparīkṣā.txt'
      work_id: WC40F9781
    752758e50dc6439e8c1eabd9ee34e7bb:
      title: 'Chapter 4: Tathāgatācintya'
      base_file: 'Chapter 4: Tathāgatācintya.txt'
      work_id: W927EFEF8
    3df431fa2e1e48f3ab239eb96a9e6bb5:
      title: 'Chapter 5: Caturbrahmavihāra'
      base_file: 'Chapter 5: Caturbrahmavihāra.txt'
      work_id: W4124B76A
    8a69da70fbe7468bbbfaa03e01987e27:
      title: 'Chapter 6: Dānapāramitā'
      base_file: 'Chapter 6: Dānapāramitā.txt'
      work_id: WBEAD883B
    f5b1f4feb1c544b6bbaec49fee63ef53:
      title: 'Chapter 7: Śīlapāramitā'
      base_file: 'Chapter 7: Śīlapāramitā.txt'
      work_id: W5754D95B
    ffa2598e2a3d44a58cff48f4f0c9a924:
      title: 'Chapter 8: Kṣāntipāramitā'
      base_file: 'Chapter 8: Kṣāntipāramitā.txt'
      work_id: W2499F951
    8b97c03c253b4362b624633a196ab0fe:
      title: 'Chapter 9: Vīryapāramitā'
      base_file: 'Chapter 9: Vīryapāramitā.txt'
      work_id: W943F99C4
    01099c2226604db1a19c5ca3df68bd44:
      title: Colophon
      base_file: Colophon.txt
      work_id: W4E5FA098
    b7284a2626b14f76afb342a004223d91:
      title: Preface
      base_file: Preface.txt
      work_id: W804C800A
    848418e4c19140e59069743e3973d92d:
      title: Title
      base_file: Title.txt
      work_id: W012AB27B
  chapter_to_tile:
    CI: 'Chapter 1: Gṛhapati'
created_at: '2022-03-01T21:18:50.215109'
last_modified_at: '2022-03-01T21:18:50.215116'
